fuse: file: Remove unused variable 'ff'
fs/fuse/file.c:1210:20: error: unused variable 'ff' [-Werror,-Wunused-variable]
        struct fuse_file *ff = file->private_data;
                          ^
1 error generated.

Change-Id: I5c187cac5870785a4679cc8b19111c8409ee5ce6