Revert "arm64: bpf: Don't use module memory for the BPF JIT CFI check."
Fix CLang compile error:
arch/arm64/net/bpf_jit_comp.c:956:18: error: use of undeclared identifier 'BPF_JIT_REGION_START'
        return (func >= BPF_JIT_REGION_START && func < BPF_JIT_REGION_END);
                        ^
arch/arm64/net/bpf_jit_comp.c:956:49: error: use of undeclared identifier 'BPF_JIT_REGION_END'
        return (func >= BPF_JIT_REGION_START && func < BPF_JIT_REGION_END);
                                                       ^
2 errors generated.

This reverts commit c1985ac4d952fc4272352590c4283f30af994d2d.

Change-Id: Ib13fd5438edbfacbcca85bc0a9b65127862180fd