goodix: Remove unused variables
drivers/input/fingerprint/goodix/gf_spi.c:281:16: error: unused variable 'gf_key' [-Werror,-Wunused-variable]
        struct gf_key gf_key;
                      ^
drivers/input/fingerprint/goodix/gf_spi.c:531:6: error: unused variable 'i' [-Werror,-Wunused-variable]
        int i;
            ^
2 errors generated.

Change-Id: Ifeed94e85c3abda52aea9f2854a9e6ce46dc6405